
# генерируется автоматически в при запуске через cobra 

api-key-binance: 
api-secret-binance: 
build-target: 
content-embed: 
db-host-docker: 
db-host-local: 
db-name: 
db-password: 
db-port: 
db-user: 
debug-log: 
exchange-type: 
grpc-host-docker: 
grpc-host-local: 
grpc-port: 
host-web: 
pairs-from-file: 
password-auth: 
production: 
production-log: 
proxy-port: 
proxy-server:
server-name: 
telegram-token: 
telegram-user: 
username-auth: 
