список стратегий для окна выбора стретегий при совершении сделки, для дальнейшего анализа

simple:
  description: "Стратегия при которой мы покупаем на дне таймфрейма и дожидаемся пика таймфрейма"
simple2:
  description: "------"
