name: exchangebot-base

services:
  exchangebot:
    container_name: exchangebot  
    build:
      context: .
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        VITE_GRAFANA_URL: ${VITE_GRAFANA_URL:-grafana}
    image: sambly/exchangebot:${EXCHANGE_BOT_TAG:-latest}  
    ports:
      - "${EXCHANGEBOT_HOST_PORT:-8080}:${EXCHANGEBOT_WEB_LISTEN_PORT:-80}"
    volumes:
      - ./log:/app/log 
      - ./configs:/app/configs
      - ./internal/strategy:/app/internal/strategy          
    environment:
      ENVIRONMENT: docker
      EXCHANGEBOT_TRACER_ENABLE_OPEN_TELEMETRY: true 
      EXCHANGEBOT_TRACER_OTEL_EXPORTER_OTLP_ENDPOINT: otel-collector:4317
      EXCHANGEBOT_TRACER_OTEL_SERVICE_NAME: exchangebot       
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - exchange
    
  mysql:
    container_name: mysql  
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${EXCHANGEBOT_DB_PASSWORD}
      MYSQL_DATABASE: ${EXCHANGEBOT_DB_NAME}
    ports:
      - "${EXCHANGEBOT_DB_PORT_HOST:-3307}:${EXCHANGEBOT_DB_PORT:-3306}"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysql --silent -u root -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 100s        
    networks:
      - exchange

  prometheus:
    container_name: prometheus  
    image: prom/prometheus
    volumes:
      - ./configs-service/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"  
    networks:
      - exchange

  grafana:
    container_name: grafana    
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - exchange

  otel-collector:
    container_name: otel-collector     
    image: otel/opentelemetry-collector-contrib:0.101.0
    command:
      - "--config"
      - "/otel-local-config.yaml"
    volumes:
      - ./configs-service/tracer/collector.config.yaml:/otel-local-config.yaml
    ports:
      - 4317:4317
    depends_on:
      jaeger:
        condition: service_started
    networks:
      - exchange 

  jaeger:
    container_name: jaeger      
    image: jaegertracing/all-in-one:latest
    restart: unless-stopped
    ports:
      - 16686:16686
      - 16685:16685
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    healthcheck:
      test: ["CMD", "wget", "--spider", "localhost:16686"]
      interval: 1s
      timeout: 3s
      retries: 60
    networks:
      - exchange

volumes:
  mysql_data:

networks:
  exchange:
    driver: bridge