# Имя стратегии
name: SaleSimple
# Id стратегии
idName: salesimple
# Описание стратегии
description: Продажа при достижении изменения цены на определенный процент
# Включение стратегии
strategyEnable : false

procent: 1.0
