# Имя стратегии
name: Base
# Id стратегии
idName: base
# Описание стратегии
description: Отслеживание цены за период для пар, формирование уведомлений и сигналов для других стратегий
# Включение стратегии
strategyEnable : false
# Включение уведомлений 
notificationEnable: false

# Проверить все пары
allPairs: true
# Выбор определенных пар 
pairs:
  - BTCUSDT
  - XRPUSDT
  - SOLUSDT
  - BNBUSDT
  - GALAUSDT
# Уставки процентов за периоды
weightProcents:
  1m: 1.0
  3m: 45.0
  15m: 40.0
  1h: 38.0
  4h: 35.0
  1d: 30.0
