# Имя стратегии
name: Simplebuy стратегия
# Id стратегии
idName: simplebuy
# Описание стратегии
description: покупка через телеграм, по сигналам base стратегии
# Включение стратегии
strategyEnable : true
# Включение уведомлений 
notificationEnable: true